import cap  from './img/1.png'
import cap1 from './img/2.png'
import cap2  from './img/3.png'
import cap3 from './img/4.png'
import cap4  from './img/5.png'
import cap5 from './img/6.png'
import cap6  from './img/7.png'
import cap7 from './img/8.png'
import cap8  from './img/9.png'
import cap9 from './img/10.png'

import nigga from './img/niggaShet.png'
import niggaTwo from './img/nigashettwo.png'
 




export const CartCard = []
 
export const news = [
  {
    "id": 1,
   
    "title": "Кастомные",
    "doit": "Создай свой стиль",
  
    "image": nigga,
  },
  {
    "id": 1,
    "title": "Эксклюзив",
    "doit": "Создай свой Найди уникальные кепки",
    "image": niggaTwo,
  }
    

]
 

export const cups = [
  {
    "id": 1,
    "brand": "Nike",
    "modal":"French Fries Series",
    "size": 'S',
    "count" : 1,
    "description": "2021",
    "price": 3800,
    "image": cap,
    "status": true,
  },
  {
      "id": 2,
      "brand": "New Era",
      "modal":"New York Yankies",
      "size": 'S',
      "count" : 1,
      "description": "2021",
      "price": 3800,
      "image": cap1,
      "status": true,
    },
    {
      "id": 3,
      "brand": "New Era",
      "modal":"Alpha Male Team",
      "size": 'X',
      "description": "2021",
      "price": 3500,
      "image": cap2,
      "count" : 1,
      "status": 'new',
    },
    {
      "id": 4,
      "brand": "Adidas",
      "modal":"Supreme Collab",
      "size": 'XS',
      "count" : 1,
      "description": "2021",
      "price": 5500,
      "image": cap3,
      "status": 'popular',
    },
    {
      "id": 5,
      "brand": "New Era",
      "modal":"Supreme Collab",
      "size": 'S',
      "count" : 1,
      "description": "2021",
      "price": 500,
      "image": cap4
    },
    {
      "id": 6,
      "brand": "DS",
      "modal":"Camo Cap Star",
      "size": 'M',
      "count" : 1,
      "description": "2021",
      "price": 3500,
      "image": cap5,
      "status": true,
    },
    {
      "id": 7,
      "brand": "Nike",
      "modal":"French Fries Series",
      "size": 'M',
      "count" : 1,
      "description": "2021",
      "price": 3500,
      "image": cap6,
      "status": true,
    },
    {
      "id": 8,
      "brand": "Nike",
      "modal":"French Fries Series",
      "size": 'S',
      "count" : 1,
      "description": "2021",
      "price": 3500,
      "image": cap7,
      "status": true,
    },
    {
      "id": 9,
      "brand": "Nike",
      "modal":"French Fries Series",
      "size": "XS",
      "count" : 1,
      "description": "2021",
      "price": 3500,
      "image": cap8,
    },
    {
      "id": 10,
      "brand": "Nike",
      "modal":"French Fries Series",
      "size": 'M',
      "count" : 1,
      "description": "2021",
      "price": 3500,
      "image": cap8,
    },
    {
      "id": 11,
      "brand": "Adidas",
      "modal":"French Fries Series",
      "size": 'XS',
      "count" : 1,
      "description": "2021",
      "price": 3500,
      "image": cap8,
    },
    {
      "id": 12,
      "brand": "Nike",
      "modal":"French Fries Series",
      "size": 'L',
      "count" : 1,
      "description": "2021",
      "price": 3500,
      "image": cap9,
    },
    {
      "id": 13,
      "brand": "Nike",
      "modal":"French Fries Series",
      "size": "XL",
      "count" : 1,
      "description": "2021",
      "price": 3500,
      "image": cap,
    },
    {
        "id": 14,
        "brand": "New Era",
        "modal":"New York Yankies",
        "size": 'XL',
        "count" : 1,
        "description": "2021",
        "price": 3800,
        "image": cap1,
      },
      {
        "id": 15,
        "brand": "New Era",
        "modal":"Alpha Male Team",
        "size": 'XL',
        "count" : 1,
        "description": "2021",
        "price": 3500,
        "image": cap2,
      },
      {
        "id": 16,
        "brand": "New Era",
        "modal":"Supreme Collab",
        "size": 'XL',
        "count" : 1,
        "description": "2021",
        "price": 5500,
        "image": cap6,
      },
      {
        "id": 17,
        "brand": "Nike",
        "modal":"French Fries Series",
        "size": 'L',
        "count" : 1,
        "description": "2021",
        "price": 3500,
        "image": cap7,
      },
      {
          "id": 18,
          "brand": "New Era",
          "modal":"New York Yankies",
          "size": 'L',
          "count" : 1,
          "description": "2021",
          "price": 3800,
          "image": cap9,
        },
        {
          "id": 19,
          "brand": "New Era",
          "modal":"Alpha Male Team",
          "size": 'S',
          "count" : 1,
          "description": "2021",
          "price": 3500,
          "image": cap4,
        },
        {
          "id": 20,
          "brand": "New Era",
          "modal":"Supreme Collab",
          "size": 'X',
          "count" : 1,
          "description": "2021",
          "price": 5500,
          "image": cap8,
          "status": false,
        },
        {
          "id": 21,
          "brand": "New Era",
          "modal":"Supreme Collab",
          "size": 'L',
          "count" : 1,
          "description": "2021",
          "price": 500,
          "image": cap6
        },
        {
          "id": 22,
          "brand": "DS",
          "modal":"Camo Cap Star",
          "size": 'M',
          "count" : 1,
          "description": "2021",
          "price": 3500,
          "image": cap5,
        },
        {
          "id": 23,
          "brand": "Nike",
          "modal":"French Fries Series",
          "size": 'M',
          "count" : 1,
          "description": "2021",
          "price": 3500,
          "image": cap,
        },
        {
          "id": 24,
          "brand": "Nike",
          "modal":"French Fries Series",
          "size": 'L',
          "count" : 1,
          "description": "2021",
          "price": 3500,
          "image": cap1,
        },
        {
          "id": 25,
          "brand": "Nike",
          "modal":"French Fries Series",
          "size": 'L',
          "count" : 1,
          "description": "2021",
          "price": 3500,
          "image": cap2,
        },
        {
          "id": 26,
          "brand": "Nike",
          "modal":"French Fries Series",
          "size": 'L',
          "count" : 1,
          "description": "2021",
          "price": 3500,
          "image": cap3,
          "status": false,
        },
        {
          "id": 27,
          "brand": "Nike",
          "modal":"French Fries Series",
          "size": 'L',
          "count" : 1,
          "description": "2021",
          "price": 3500,
          "image": cap4,
          "status": false,
        },
        {
          "id": 28,
          "brand": "Nike",
          "modal":"French Fries Series",
          "size": 'L',
          "count" : 1,
          "description": "2021",
          "price": 3500,
          "image": cap5,
          "status": false,
        },
        {
          "id": 29,
          "brand": "Nike",
          "modal":"French Fries Series",
          "size": 'L',
          "count" : 1,
          "description": "2021",
          "price": 3500,
          "image": cap6,
          "status": false,
        },
        {
            "id": 30,
            "brand": "New Era",
            "modal":"New York Yankies",
            "size": 'L',
            "count" : 1,
            "description": "2021",
            "price": 3800,
            "image": cap7,
          },
          {
            "id": 31,
            "brand": "New Era",
            "modal":"Alpha Male Team",
            "size": 'L',
            "count" : 1,
            "description": "2021",
            "price": 3500,
            "image": cap8,
          },
          {
            "id": 32,
            "brand": "New Era",
            "modal":"Supreme Collab",
            "size": 'L',
            "count" : 1,
            "description": "2023",
            "price": 2500,
            "image": cap9,
          },
          {
            "id": 33,
            "brand": "Reebok",
            "modal":"Supreme Collab",
            "size": 'M',
            "count" : 1,
            "description": "2022222",
            "price": 60000,
            "image": cap3,
          },
  
     
  ]
console.log(cups);